image: node:9.11.1

pages:
  script:
  - npm install
  - npm run generate-countries
  - npm run website:copy-flags
  - npm run website:generate-flags-page
  - cp --recursive ./website/* ./public/

  artifacts:
    paths:
    - public

  only:
  - master
